myshell: myshell.c
	gcc -Wall -o myshell myshell.c

myshell_extracredit: myshell_extracredit.c
	gcc -Wall -o myshell_extracredit myshell_extracredit.c

# Make all
#all: myshell
all: myshell myshell_extracredit

# Make clean
clean:
#	rm myshell
	rm myshell myshell_extracredit
