copyit: copyit.c
	gcc -Wall -o copyit copyit.c

copyit_extracredit: copyit_extracredit.c
	gcc -Wall -o copyit_extracredit copyit_extracredit.c

# Make all
all: copyit copyit_extracredit

# Make clean
clean:
	rm copyit copyit_extracredit
